# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Junichi Hata"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "rust"
manifest_version = 2
name = "ipacl"
service_id = "DGeefMADBYWfgQ6GZP5Jd2"

[scripts]
  build = "cargo build --bin ipacl --release --target wasm32-wasi --color always"
